defmodule FactoryMan.Params do
  @moduledoc """
  Utilities for converting Ecto structs to clean param maps.

  These functions are used by the generated `build_*_params` and `build_*_string_params`
  factory functions. You generally don't need to call them directly.
  """

  @doc """
  Strip Ecto metadata from a struct, returning a plain map suitable for changesets or API tests.

  Specifically:
  - Removes `__meta__` and autogenerated IDs
  - Removes `belongs_to` association structs (but sets FK if the association is persisted)
  - Recursively strips nested `has_one`/`has_many` associations and embeds
  - Removes `Ecto.Association.NotLoaded` values
  """
  def strip(%{__struct__: _} = record) do
    record
    |> set_persisted_belongs_to_ids()
    |> handle_assocs()
    |> handle_embeds()
    |> drop_ecto_fields()
  end

  def strip(map) when is_map(map), do: map

  @doc """
  Recursively convert atom keys to string keys. Structs and other non-map values are left
  untouched.
  """
  def stringify_keys(%{__struct__: _} = struct), do: struct

  def stringify_keys(map) when is_map(map) do
    Enum.reduce(map, %{}, fn {key, value}, acc ->
      Map.put(acc, to_string(key), stringify_keys(value))
    end)
  end

  def stringify_keys(list) when is_list(list), do: Enum.map(list, &stringify_keys/1)
  def stringify_keys(value), do: value

  # ── Private helpers ──────────────────────────────────────────────

  defp drop_ecto_fields(%{__struct__: struct} = record) do
    record
    |> Map.from_struct()
    |> Map.delete(:__meta__)
    |> drop_autogenerated_ids(struct)
  end

  defp drop_ecto_fields(record), do: record

  defp drop_autogenerated_ids(map, struct) do
    case struct.__schema__(:autogenerate_id) do
      {name, _source, _type} -> Map.delete(map, name)
      {name, _type} -> Map.delete(map, name)
      nil -> map
    end
  end

  defp set_persisted_belongs_to_ids(%{__struct__: struct} = record) do
    associations = struct.__schema__(:associations)

    Enum.reduce(associations, record, fn association_name, record ->
      association = struct.__schema__(:association, association_name)

      with %{__struct__: Ecto.Association.BelongsTo} <- association,
           belongs_to <- Map.get(record, association_name),
           %{__meta__: %{__struct__: Ecto.Schema.Metadata, state: :loaded}} <- belongs_to do
        primary_key = Map.get(belongs_to, association.related_key)
        Map.put(record, association.owner_key, primary_key)
      else
        _ -> record
      end
    end)
  end

  defp handle_assocs(%{__struct__: struct} = record) do
    associations = struct.__schema__(:associations)

    Enum.reduce(associations, record, fn association_name, record ->
      case struct.__schema__(:association, association_name) do
        %{__struct__: Ecto.Association.BelongsTo} ->
          Map.delete(record, association_name)

        _ ->
          record
          |> Map.get(association_name)
          |> handle_assoc(record, association_name)
      end
    end)
  end

  defp handle_assoc(%{__meta__: %{__struct__: Ecto.Schema.Metadata}} = assoc, record, name) do
    Map.put(record, name, strip(assoc))
  end

  defp handle_assoc(nil, record, name) do
    Map.put(record, name, nil)
  end

  defp handle_assoc(list, record, name) when is_list(list) do
    Map.put(record, name, Enum.map(list, &strip/1))
  end

  defp handle_assoc(%{__struct__: Ecto.Association.NotLoaded}, record, name) do
    Map.delete(record, name)
  end

  defp handle_embeds(%{__struct__: struct} = record) do
    embeds = struct.__schema__(:embeds)

    Enum.reduce(embeds, record, fn embed_name, record ->
      record
      |> Map.get(embed_name)
      |> handle_embed(record, embed_name)
    end)
  end

  defp handle_embed(%{} = embed, record, name) do
    Map.put(record, name, strip(embed))
  end

  defp handle_embed(list, record, name) when is_list(list) do
    Map.put(record, name, Enum.map(list, &strip/1))
  end

  defp handle_embed(nil, record, name) do
    Map.delete(record, name)
  end
end
